rideshare/urls.py
from django.conf.urls.defaults import url, patterns, include
from django.views.decorators.http import require_GET, require_POST
from . import views, admin
from occupywallst import utils
 
#adminsite = admin.AdminSite(name='rideshareadmin') 

urlpatterns = patterns('rideshare',
    #rides
    url(r'^$', 'views.rides', name='rides'),
    url(r'^create/$', 'views.ride_create', name='ride_create'),
    url(r'^(?P<ride_id>\d+)/$', 'views.ride_info', name='ride_info'),
    url(r'^(?P<ride_id>\d+)/delete/$', 'views.ride_delete', name='ride_delete'),
    url(r'^(?P<ride_id>\d+)/edit/$', 'views.ride_edit', name='ride_edit'),
    #ride requests
    url(r'^(?P<request_id>\d+)/request/view/$', 'views.ride_request_view', name='ride_request_view'),
    url(r'^(?P<ride_id>\d+)/request/add/$', 'views.ride_request_add_update', name='ride_request_add_update'),
    url(r'^(?P<ride_id>\d+)/request/delete/$', 'views.ride_request_delete', name="ride_request_delete"),
    #ride ajax
    url(r'^api/safe/rides/$', require_GET(utils.api_view(views.rides_get))),
    url(r'^api/ride_request_update/$', require_POST(utils.api_view(views.ride_request_update)), name="ride_request_update"),
    #url(r'^api/ride_edit_rendezvous/$', require_POST(utils.api_view(views.ride_edit_rendezvous)), name="ride_edit_rendezvous"),  
    #url(r'^admin/', include(adminsite.urls)),
)

rideshare/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, LineString
from django.contrib.auth.models import User, Group

from occupywallst import geo

class Ride(models.Model):
    """Info about a person or bus driving to Event for carpooling"""
    RIDETYPE_CHOICES = (
        ('car', 'Car'),
        ('bus', 'Bus'),
        ('other', 'Other'),
    )
    #this is defined twice?
    RIDEDIR_CHOICES = (
        ('round', 'Round Trip'),
        ('to', 'One Way too'),
        ('from', 'One Way from'),
    )
    
    ride_direction = models.CharField(max_length=32, choices=RIDEDIR_CHOICES,
            default="round", help_text="""
        What direction are you going?""")
        
    user = models.ForeignKey(User, editable=False, help_text="""
        User who is driving to event.""")
    published = models.DateTimeField(auto_now_add=True, blank=True, help_text="""
        When was ride posted on the site?""")
    ridetype = models.CharField(max_length=32, choices=RIDETYPE_CHOICES,
                                help_text="""
        What type of vehicle is being offered?""")
    title = models.CharField(max_length=255, help_text="""
        A one-line title to describe ride.""")
    depart_time = models.DateTimeField(default="2012-05-15", help_text="""
       What time are you leaving?""")
    return_time = models.DateTimeField(default="2012-05-22", help_text="""
        What time are you coming back?""")
    seats_total = models.IntegerField(default=0, help_text="""
        How many seats in vehicle does the user wish to fill?""")
    waypoints = models.TextField(help_text="""
        List of addresses intersected by driving route separated by newlines.
        Must contain at least two lines for origin and destination.  This may
        be updated to include people who will be picked up.""")
    waypoints_points = models.LineStringField(null=True, default=None, help_text="""
        the points to the address of the waypoints""")
    route = models.LineStringField(null=True, default=None, help_text="""
        The driving route coords Google gave us from waypoints.""")
    route_data = models.TextField(blank=True, help_text="""
        Google's goofy compressed version of route coords.""")
    info = models.TextField(blank=True, help_text="""
        A little bit about yourself, the ride, and what to expect""")
    #forum_post = models.ForeignKey(ForumPost, null=True, blank=True)
    is_deleted = models.BooleanField(default=False, editable=False,
                                     help_text="""
        Flag to indicate should no longer be listed on site.""")
    objects = models.GeoManager()

    class Meta:
        unique_together = ("user", "title")

    def __unicode__(self):
        if self.ridetype == 'other':
            return "%s's ride" % (self.user)
        else:
            return "%s's %s ride" % (self.user, self.ridetype)

 #   def delete(self):
  #      self.is_deleted = True
  #      self.save()
  #      super(Ride, self).delete(*args, **kwargs) # Call the "real" save() method.



    @property
    def pending_requests(self):
        return self.requests.filter(status="pending")

    @property
    def accepted_requests(self):
        return self.requests.filter(status="accepted")

    def forum_title(self):
        waypoints = self.waypoint_list
        return "%s to %s on %s" % (
                waypoints[0], waypoints[-1], self.depart_time.date())

    def retrieve_route_from_google(self):
        route = geo.directions(self.waypoint_list)
        points = []
        for waypoint in route:
            flip_me = waypoint['overview_polyline']['points']
            points += [(x, y) for y, x in flip_me]
        self.route = LineString(points)

    @property
    def waypoint_list(self):
        return [s.strip() for s in self.waypoints.split('\n') if s.strip()]
        
    @property
    def seats_avail(self):
        accepted_requests = self.accepted_requests
        total = 0
        for item in accepted_requests:
            total = item.seats_wanted + total
        return self.seats_total - total

    @models.permalink
    def get_absolute_url(self):
        return ('rideshare.views.ride_info', [self.id])

class RideRequest(models.Model):
    """List of pending/accepted/denied Ride requests

    This table if for requests sent *to* a user offering a ride.
    """
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected'),
    )

    RIDEDIR_CHOICES = (
        ('round', 'Round Trip'),
        ('to', 'One Way too'),
        ('from', 'One Way from'),
    )



    ride = models.ForeignKey(Ride, editable=False,
                             related_name="requests", help_text="""
        The ride the user wants to get in on.""")
    user = models.ForeignKey(User, help_text="""
        The user who needs a ride to the event.""")
    status = models.CharField(max_length=32, choices=STATUS_CHOICES,
            default="pending", help_text="""
        Current acceptance status of request.""")
        
    ride_direction = models.CharField(max_length=32, choices=RIDEDIR_CHOICES,
            default="round", help_text="""
        What direction are you going?""")

    info = models.TextField(blank=True, help_text="""
        User explains why they think they deserve a ride.""")
    is_deleted = models.BooleanField(default=False, editable=False,
                                     help_text="""
        Flag to indicate should no longer be listed on site.""")
    #maybe implement later
    seats_wanted = models.IntegerField(default=1, help_text="""
        how many seats the person is going to take up""")
    
    rendezvous = models.PointField(null=True, blank=True, help_text="""
        Aproximate coordinates of where they live to display on the
        attendees map.""")
        
    rendezvous_address = models.TextField(blank=True, help_text="""
        the address given by reverse geocoding the rendezvous point""")
    
    objects = models.GeoManager()

    @property
    def accepted(self):
        return (self.status == "accepted")

    @property
    def declined(self):
        return (self.status == "declined")

    class Meta:
        unique_together = ("ride", "user")

    def __unicode__(self):
        return "%s wants seat in %s" % (self.user, self.ride)
    
    #this is also defined twice
    rendezvous_lat = property(lambda s: s.rendezvous.y if s.rendezvous else None)
    rendezvous_lng = property(lambda s: s.rendezvous.x if s.rendezvous else None)
    rendezvous_latlng = property(
        lambda s: (s.rendezvous.y, s.rendezvous.x) if s.rendezvous else None,
        lambda s, v: setattr(s, 'rendezvous', Point(v[1], v[0])))

    @classmethod
    def fetch(cls, ride, user):
        if not ride or not user:
            return None
        try:
            return cls.objects.get(ride=ride, user=user)
        except ObjectDoesNotExist:
            return None

rideshare/forms.py
r"""

    rideshare.forms
    ~~~~~~~~~~~~~~~~~~

    HTML form definitions.

"""
from django import forms
from rideshare import models as db

class RideForm(forms.ModelForm):

    class Meta:
        model = db.Ride
        fields = ( 'title','info','ridetype', 'seats_total', 'ride_direction','depart_time','return_time','start_address','end_address','waypoints','waypoints_points')
        exclude = ['published','seats_used', 'route', 'route_data', 'forum_post','waypoints_points']
        
    start_address = forms.CharField(required=True)
    end_address = forms.CharField(required=True)
    waypoints = forms.CharField(required=False, widget=forms.Textarea, help_text="""Add other adresses or destinations separated by newlines to make you route more accurate""")
    waypoints_points_wkt = forms.CharField(required=False, widget=forms.HiddenInput)
    
    def __init__(self, *args, **kwargs):
        
        super(RideForm,self).__init__(*args,**kwargs)
        self.fields['seats_total'].label = "Seats available"
        self.fields['waypoints'].label = "Waypoints(optional)"
        self.fields['info'].label = "Ride Description"
        
        if kwargs.has_key('instance') and kwargs['instance']:
            instance = kwargs['instance']
            #pdb.set_trace()
            self.initial['waypoints_points_wkt'] = instance.waypoints_points
            self.initial['start_address'] = instance.waypoint_list[0]
            self.initial['end_address'] = instance.waypoint_list[-1]
            self.initial['waypoints'] = '\n'.join(instance.waypoint_list[1:-1])
            
    def save(self, commit=True):
        from django.contrib.gis.geos import GEOSGeometry
        model = super(RideForm, self).save(commit=False)
        
        points = GEOSGeometry(self.cleaned_data['waypoints_points_wkt'])
        #pdb.set_trace()
        model.waypoints_points = points 
        
        if self.cleaned_data['waypoints'] != '':
            self.cleaned_data['waypoints'] = self.cleaned_data['waypoints'] + '\n'
        model.waypoints = self.cleaned_data['start_address'] + "\n" + self.cleaned_data['waypoints'] + self.cleaned_data['end_address']
        if commit:
            model.save()
        return model
        
class RideRequestForm(forms.ModelForm):
    class Meta:
        model = db.RideRequest
        exclude = ('rendezvous','user','status')
        
    rendezvous_lat = forms.FloatField(required=False,widget=forms.HiddenInput)
    rendezvous_lng = forms.FloatField(required=False,widget=forms.HiddenInput)
    rendezvous_address =  forms.CharField(required=False, widget=forms.HiddenInput)
    seats_wanted = forms.IntegerField(required=False, widget=forms.Select)
    
    #Override the constructor to manually set the form's latitude and
    # longitude fields if a Location instance is passed into the form
    def __init__(self,  *args, **kwargs):
        super(RideRequestForm, self).__init__(*args, **kwargs)
 
        # Set the form fields based on the model object
        if kwargs.has_key('instance')  and kwargs['instance']:
            instance = kwargs['instance']
            self.initial['rendezvous_lat'] = instance.rendezvous_lat
            self.initial['rendezvous_lng'] = instance.rendezvous_lng         

    def save(self, commit=True):
        #commit = kwargs.pop('commit', True)
        model = super(RideRequestForm, self).save(commit=False)
        
        # Save the latitude and longitude based on the form fields
        model.rendezvous_latlng =self.cleaned_data['rendezvous_lng'], self.cleaned_data['rendezvous_lat']
        
        if commit:
            model.save()
        return model

rideshare/templates/request_view.html
{% extends base %}
{% load ows %}

{% block title %}Free Bus/Carpool Route Map | {{ OWS_SITE_NAME }}{% endblock title %}

{% block stylesheets %}
  <style type="text/css">
      #id_ride_alt{
        text-decoration: none; 
        background-color: #11264E;
        background: url(/media/img/strip-dark.png);
        color:#EBEBEB;
    }
  </style>
{% endblock stylesheets %}

{% block scripts %}
  <script src="//maps.google.com/maps/api/js?libraries=places&sensor=false&region=us" type="text/javascript"></script>
{% endblock scripts %}

{% block js_init %}
  {{ block.super }}
  maps_init({
    "map": document.getElementById("map"),
    "zoom": 8,
    "initial_polyline": [{% for point in ride.route %}[{{point.1}},{{point.0}}],{%endfor%}],  
    {% if ride_request %} 
    "marker": [{{ride_request.rendezvous.0}},{{ride_request.rendezvous.1}}],
    "address":"<b>rendezvous point</b><br> {{ride_request.rendezvous_address}}",
    {% else %} {% if ride.user != request.user %}
	 "marker":null,
	 "draggable":true,
    {% endif %}{% endif %}
  });
{% endblock js_init %}


{% block content %}
<section id="rides" style="padding-top:10px">
<div style="float:left ">
    <h1>Info for </h1>{{ride_request.user|userlink }}  <h1>ride request</h1>
    {% if user == ride_request.user %}
    <a href="{% url ride_edit ride.id %}">edit</a> <a href="{% url ride_delete ride.id %}">delete</a></form>
    {% endif %}
    <h2>{{ ride.get_ridetype_display }} leaving {{ ride.depart_time }}</h2>
    {{ ride.info|markup }}

    <p>{{ ride.seats_avail }} seats available</p>
    {% if ride.user == request.user %}
    <p>Ride requests</p>
    <form class="request_accept_form" method="POST" action="{% url ride_request_update %}">{% csrf_token %}
        <table>
        <tr>
            <td>Info:{{ride_request.info}}<td>
        </tr>
        <tr>
            <td>Rendezvous Address:{{ride_request.formatted_address}}<td>
        </tr>
        <tr>
            <!--<td>Add rendezvous point to waypoints? <input type="checkbox" value="true"></input><td> -->
        </tr>
        <tr>
            <td><a href="{{req.user.get_absolute_url}}">{{ride_request.user.username}}:</a></td>
            <td>{{ride_request.info}}</td>
            <td>
                
                <input type="hidden" name="request_id" value="{{req.id}}"/>
                <select name="status">
                    <option value="pending" {% if req.status = "pending" %}selected{% endif %}>Pending</option>
                    <option value="accepted"{% if req.status = "accepted" %}selected{% endif %}>Accept</option>
                    <option value="declined"{% if req.status = "declined" %}selected{% endif %}>Decline</option>
                </select>
                
            </td>
            <td><div class="req-status">{% if req.accepted %}☺{%else%}{%if req.declined %}☹{%endif%}{%endif%}</div></td>
            </tr>
        </table>
        {% endif %}

    </form>
    <div style="width: 60%; height: 500px; float:right" " id="map"></div>
</div>
</section>
{% endblock content %}

rideshare/templates/ride_base.html
{% extends base %}

{% block title %}Free Bus/Carpool Route Map | {{ OWS_SITE_NAME }}{% endblock title %}
{% block body_class %}rides-page{% endblock %}
{% block scripts %}
  <script src="//maps.google.com/maps/api/js?libraries=places&sensor=false&region=us" type="text/javascript"></script>
{% endblock scripts %}

{% block stylesheets %}
  <style type="text/css">
      #id_rides{
        text-decoration: none; 
        background-color: #11264E;
        background: url(/media/img/strip-dark.png);
        color:#EBEBEB;
    }
  </style>
{% endblock stylesheets %}

{% block content %}
<section id="rides" style="padding-top:10px;padding-bottom:10px">
    {% block ride_content %}
    
    {% endblock ride_content %}
</section>
<div clear="both" style="padding-bottom: 10px;"></div>
{% endblock content %}

rideshare/templates/ride_info.html
{% extends "ride_base.html" %}


{% block js_init %}
  {{ block.super }}
  maps_init({
    "map": document.getElementById("map"),
    "zoom": 8,
    "initial_polyline": [{% for point in ride.route %}[{{point.1}},{{point.0}}],{%endfor%}],  
    {% if ride_request %} 
    "marker": [{{ride_request.rendezvous.0}},{{ride_request.rendezvous.1}}],
    "address":"<b>rendezvous point</b><br> {{ride_request.rendezvous_address}}",
    {% else %} {% if ride.user != request.user %}
	 "marker":null,
	 "draggable":true,
    {% endif %}{% endif %}
    {% if requests %}
		"rendezvous":[{% for request in requests %}[{{request.rendezvous.0}},{{request.rendezvous.1}},"{{request.rendezvous_address}}","{{request.user}}"],{%endfor%}],
    {% endif %}
  });
  
  $('#cancel_ride').click(function(e){
		
		confirm("are you sure you want to cancel?");
	  });
{% endblock js_init %}


{% block ride_content %}
    <div style="float:left; width: 23%;">
    <h1>Info for {{ ride.title }}</h1>
    {% if user == ride.user %}
    <a href="{% url ride_edit ride.id %}">edit</a> <a href="{% url ride_delete ride.id %}">delete</a></form>
    {% else %}
	<a href="{{ride.user.get_absolute_url}}">Message {{ride.user.username}}:</a>
    {% endif %}
    <h2>{{ ride.get_ridetype_display }} going {{ ride.get_ride_direction_display }}</h2>
    leaving: {{ ride.depart_time|date:"SHORT_DATE_FORMAT" }}
    {% if ride.ride_direction == "round" %}
	<br>returning: {{ ride.return_time|date:"SHORT_DATE_FORMAT" }}
    {% endif %}
    
    <p>{{ ride.info }}</p>
    <h3>Destinations</h3>
    <ol>
        {% for waypoint in ride.waypoint_list %}
        <li>{{waypoint}}</li>
        {% endfor %}
    </ol>
    <p>{{ ride.seats_avail }} seats available</p>
    {% if ride.user == request.user %}
    <p>Ride requests</p>

    {% for req in requests %}
        <h3>Request for {{req.seats_wanted}} seat{% if req.seats_wanted != 1 %}s{% endif %}<br>
				Going {{ req.get_ride_direction_display }}
			</h3>
			<div style="border-style:solid;border-width:1px;padding:5px">{{req.info}}</div>
			<div style="white-space:nowrap;">
            <form style="float:left" class="request_accept_form" method="POST" action="{% url ride_request_update %}">
                {% csrf_token %}
                <input type="hidden" name="request_id" value="{{req.id}}"/>
                <select name="status">
                    <option value="pending" {% if req.status = "pending" %}selected{% endif %}>Pending</option>
                    <option value="accepted"{% if req.status = "accepted" %}selected{% endif %}>Accept</option>
                    <option value="declined"{% if req.status = "declined" %}selected{% endif %}>Decline</option>
                </select>
            </form>
            <a href="{{req.user.get_absolute_url}}">Message {{req.user.username}}:</a>
            </div><br>
 
    {% empty %}
    No pending requests

    {% endfor %}

    {% else %}
	<!-- view ride request -->	

    {% if ride_request %}
		{% comment %} 
		{{ form.rendezvous_lat }}
		{{ form.rendezvous_lng }}
		{{ form.ride_dir }}
		{{ form.seats_wanted }}
		{{ form.rendezvous_address }}
		{% endcomment %}
		<div id="requeststatus">
			{% if ride_request.status = "pending" %}
			You have requested {{ride_request.seats_wanted}} seats,<br>
			going {{ ride_request.get_ride_direction_display }}
			{% else %}
			{% if ride_request.status == "accepted" %}
			You have {{ride_request.seats_wanted}} seat this ride.
			{% else %}
			{% if ride_request.status == "reject" %}
			Your ride request has been rejected.
			{% endif %}
			{% endif %}
			{% endif %}
		</div>
		<br>
		<a id="cancel_ride"  href={% url ride_request_delete ride.id %}>cancel ride request</a>
        <br><br>
		{#<button type="submit" style="visibility:hidden" id="edit_rendezvous">Update Rendezvous</button>#}
    {% else %}
    <!-- request a ride -->
		<form method="POST" action={% url ride_request_add_update ride.id%}>{%csrf_token%}
		{{ form.non_field_errors }}
		{{ form.rendezvous_lat }}
		{{ form.rendezvous_lng }}
		{{ form.rendezvous_address }}
		<h2>Want a seat?</h2>
		    
			{{ form.info.errors }}
			<label for="id_info"> <h3>Step 1.Tell us about yourself</h3></label>
			{{ form.info }}
			
			{{ form.ride_direction.errors }}
			<label for="id_ride_dir">What way do you want to go?:</label>
			{{ form.ride_direction }}
			
			{{ form.seats_wanted.errors }}
			<label for="id_seats_wanted">How many seats do you need?:</label>
			{{ form.seats_wanted }}
			
        <h3>Step 2.Use the maker to select an approximant rendezvous Point</h3>
		<input id="submit" disabled="disabled"  type="submit" value="Request a seat"/> 	    
		</form>
    {% endif %}
    {% endif %}
    </div>
    <div  style="width: 75%; height: 500px; float:right;" id="map"></div>

{% endblock ride_content %}

rideshare/templates/ride_update.html
{% extends base %}
{% block body_class %}rides-page rides-update-page{% endblock %}
{% block title %}Free Bus/Carpool Route Map | {{ OWS_SITE_NAME }}{% endblock title %}
	
{% block scripts %}
  <link type="text/css" href="{{ MEDIA_URL }}css/custom-theme/jquery-ui-1.8.17.custom.css" rel="Stylesheet" />	
  <script src="//maps.google.com/maps/api/js?libraries=places&sensor=false&region=us" type="text/javascript"></script>
{% endblock scripts %}

{% block js_init %}
  {{ block.super }}
  rides_init({
    "map": document.getElementById("map"),
    "center": new google.maps.LatLng(41.87723,-87.629013),
    {% if ride.route %}
     "initial_polyline": [{% for point in ride.route %}[{{point.1}},{{point.0}}],{%endfor%}],  
    {% endif %}
    "zoom": 8,
    {% if requests %}
		"rendezvous":[{% for request in requests %}[{{request.rendezvous.0}},{{request.rendezvous.1}},"{{request.rendezvous_address}}","{{request.user}}"],{%endfor%}],
    {% endif %}
  });
{% endblock js_init %}

{% block content %}
{% if ride %}
<h1>Update {{ride.title}}</h1>
{% else %}
<h1>Add a ride</h1>
{% endif %}
<table style="width:100%"><tbody><tr><td id="left">
    <form method="POST" action=".">{% csrf_token %}
        <table class="formtable">
            <tbody>
                {{ form.as_table }}
                <tr><th></th><td><input type="submit" value="{% if ride %}Update{% else %}Add{%endif%} ride"/></td></tr>
            </tbody>
        </table>
    </form>
    </td><td id="mapright">
    <div style="height: 500px" id="map">

    </div>
</td></tr>
</tbody>
</table>

{% endblock content %}

rideshare/templates/rides.html
{% extends "ride_base.html" %}

{% block js_init %}
  {{ block.super }}
  rides_init({
    "map": document.getElementById("map"),
    "center": new google.maps.LatLng(41.87723,-87.629013),
    "zoom": 5,
    "update_rides" : true,
  });
{% endblock js_init %}



{% block ride_content %}
    <div style="float:left ">
        <h1>
          Bus/Carpool

          <img id="loader" style="display:none" src="{{ MEDIA_URL }}img/ajax-loader.gif" width="16" height="16" />
        </h1>
          <nav>
            {% if user_ride %}
                <a href="{% url ride_info user_ride.id %}">View Your Ride</a>
            {% else %}{% if user_ride_request %}
                <a href="{% url ride_info user_ride_request.ride.id %}" >View Your Ride Request</a>
            {% else %}
                <a href="{% url ride_create %}">Add a ride</a>
            {% endif %}{% endif %}
          </nav>
        <br><br>
        <div style="border-style:solid; border-width:1px; padding:3px; width:220px">
            <b>Map Key</b><br>
            Click on a line to view the ride and request a seat.<br><br>
            Blue markers stand as starting points for rides. 
        </div>
    </div>
    <div style="width: 75%; height: 500px; float:right" id="map"></div>
{% endblock ride_content %}